name: Test loading benchmark data

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Install dependencies
      working-directory: benchmark
      run: |
        uv sync

    - name: Setup benchmark
      working-directory: benchmark
      run: uv run 01_setup_benchmark.py --config_path benchmark_config.ci.yaml --save_path benchmark_data.db
